//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaintMeter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PortCom {
            get {
                return ((string)(this["PortCom"]));
            }
            set {
                this["PortCom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetDateTimeOption {
            get {
                return ((bool)(this["SetDateTimeOption"]));
            }
            set {
                this["SetDateTimeOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetPortMeterOption {
            get {
                return ((bool)(this["SetPortMeterOption"]));
            }
            set {
                this["SetPortMeterOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\Measurements\\")]
        public string FolderOfMeasurements {
            get {
                return ((string)(this["FolderOfMeasurements"]));
            }
            set {
                this["FolderOfMeasurements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\DataDetails\\")]
        public string FolderOfDataDetails {
            get {
                return ((string)(this["FolderOfDataDetails"]));
            }
            set {
                this["FolderOfDataDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\Autos\\")]
        public string FolderOfAuto {
            get {
                return ((string)(this["FolderOfAuto"]));
            }
            set {
                this["FolderOfAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAutomaticSearchPort {
            get {
                return ((bool)(this["IsAutomaticSearchPort"]));
            }
            set {
                this["IsAutomaticSearchPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAutomaticDateTime {
            get {
                return ((bool)(this["IsAutomaticDateTime"]));
            }
            set {
                this["IsAutomaticDateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int IntervalConnectTimer {
            get {
                return ((int)(this["IntervalConnectTimer"]));
            }
            set {
                this["IntervalConnectTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int IntervalCheckExistingPortTimer {
            get {
                return ((int)(this["IntervalCheckExistingPortTimer"]));
            }
            set {
                this["IntervalCheckExistingPortTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\Conclusions\\")]
        public string FolderOfConclusions {
            get {
                return ((string)(this["FolderOfConclusions"]));
            }
            set {
                this["FolderOfConclusions"] = value;
            }
        }
    }
}
